// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPKRzrZhavGLMbewt_n71EgzNX_5MpSL8',
    appId: '1:1063834909170:web:c0bcce385b7606ff35136b',
    messagingSenderId: '1063834909170',
    projectId: 'food-delivery-72100',
    authDomain: 'food-delivery-72100.firebaseapp.com',
    storageBucket: 'food-delivery-72100.firebasestorage.app',
    measurementId: 'G-8B7BECE8TQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8eQp-BLdzAAK6Dp1iPvYh0xHUH3_MHGs',
    appId: '1:1063834909170:android:45e239891dd346a735136b',
    messagingSenderId: '1063834909170',
    projectId: 'food-delivery-72100',
    storageBucket: 'food-delivery-72100.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAUdPKMwXF0xBSMExFiADX4AeIu0XUnTg',
    appId: '1:1063834909170:ios:3388645a6a45ad0835136b',
    messagingSenderId: '1063834909170',
    projectId: 'food-delivery-72100',
    storageBucket: 'food-delivery-72100.firebasestorage.app',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAUdPKMwXF0xBSMExFiADX4AeIu0XUnTg',
    appId: '1:1063834909170:ios:3388645a6a45ad0835136b',
    messagingSenderId: '1063834909170',
    projectId: 'food-delivery-72100',
    storageBucket: 'food-delivery-72100.firebasestorage.app',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPKRzrZhavGLMbewt_n71EgzNX_5MpSL8',
    appId: '1:1063834909170:web:73c36790a54396ef35136b',
    messagingSenderId: '1063834909170',
    projectId: 'food-delivery-72100',
    authDomain: 'food-delivery-72100.firebaseapp.com',
    storageBucket: 'food-delivery-72100.firebasestorage.app',
    measurementId: 'G-D4SBPVTCZX',
  );
}
